name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            openjdk-11-jdk \
            unzip \
            git \
            python3-pip \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            libunwind-dev \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libssl-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            libncursesw5-dev \
            libffi-dev

          pip install buildozer
          
      - name: Create Buildozer
        run: |
          buildozer init
          
      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
        env:
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: bin/*.apk
